language: php
php:
    - '7.0'
    - '7.1'
install:
    composer install --no-interaction
before_script:
    phpenv config-add php.ini
script:
    phpunit --group=PrometheusExporter --configuration phpunit.xml
